FROM python:2.7.9
MAINTAINER Tom Steele <tom@stacktitan.com>

RUN wget https://github.com/fishnetsecurity/Lair-Drones/releases/download/1.0.0/lairdrone-1.0.0.tar.gz&& pip install lairdrone-1.0.0.tar.gz

VOLUME ["/data"]
